### ISSUE TITLE
[iOS] Sometimes crash app when open document view

### ISSUE THREAD

**Issue by hatn98** [PDFTron/pdftron-react-native#282] opened 2021-05-28 04:25 UTC
**Describe the bug**
Sometimes when I open the document (I build with `react-native-pdftron latest` master version and `PDFNet (9.0.0.77669) Pod`) - crash app with error: `RNTPTDocumentController.m:221:5: '[' - Thread 1: signal SIGABRT`

**Steps to Reproduce the Problem**
1. Create new react app or replace "react-native-pdftron": "file:../" in example app for "react-native-pdftron": github:PDFTron/pdftron-react-native
2. Install all dependencies
3. Open a file pdf by "react-native-pdftron"

**Screenshots**
Here is the screenshots for this issue:

<img width="328" alt="Screen Shot 2021-05-28 at 11 03 49" src="https://user-images.githubusercontent.com/74538611/119928973-d4c3a500-bfa6-11eb-92bd-2fe1b8d095cf.png">
This is the log in Xcode:
<img width="866" alt="Screen Shot 2021-05-28 at 11 19 45" src="https://user-images.githubusercontent.com/74538611/119928920-c2e20200-bfa6-11eb-857d-46ea16437677.png">

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: `iOS`

**Comment by JamieDass** [comment] 2021-06-01 15:21
Hi @hatn98,

Unfortunately we were unable to reproduce this issue. Are you able to share some more information about the problem?
You said that it only sometimes happens is that right? Does it only happen for certain documents or on certain devices/simulators? Are you aware of any other steps needed to reproduce the crash?
Any other additional information which might help us reproduce the problem would be helpful.

**Comment by hatn98** [comment] 2021-06-02 16:06
Thank you for your reply,
_1. You said that it only sometimes happens is that right?_
**-> Yes, it happens sometimes.**
_2. Does it only happen for certain documents or on certain devices/simulators_
**-> No, it happens with all documents and all devices/simulators.**
_3. Are you aware of any other steps needed to reproduce the crash?_
**-> I don't know, I just need to open the documents continuity and it happens.**

This is the video link that I reproduce the issue: 
https://youtu.be/0Soyh7ux8Ok
I tried to open documents by your repo example with the latest version.
In the video, I opened it about 15 times and it showed the issue.
But with my project was more configurable, so I opened it about 6-7 times and it was crashed.
I hope you can try to reproduce this issue.

**Comment by JamieDass** [comment] 2021-06-08 00:56
Hi @hatn98,

Just wanted to let you know that we are investigating this issue and will hopefully have an update for you soon

**Comment by JamieDass** [comment] 2021-06-08 17:50
Hi @hatn98,

Just a quick follow up, yesterday we released a new version of the native iOS SDK — v9.0.1.77780. Are you able to update (rerun `pod install`) and let us know if the issue is still happening with the latest version?

**Comment by hatn98** [comment] 2021-06-09 07:22
Hi @JamieDass,
I tried with the new version and it doesn't seem to crash anymore.
Thank you so much.

**Comment by JamieDass** [comment] 2021-06-10 15:52
Hi @hatn98,

Great we're glad to hear it! I'll close this issue now.

**Closed by JamieDass** 2021-06-10 15:52 UTC
Labels: bug, ios
