### ISSUE TITLE
Replies to comments not shown

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#513] opened 2022-03-03 14:08 UTC
Hello, 
On web after adding a comment to an annotation, I add 2 replies to it and it is displayed like this on web;

<img width="254" alt="Screenshot 2022-03-03 at 15 06 47" src="https://user-images.githubusercontent.com/49630919/156580551-a4a45605-3d45-45be-9a40-ad0655792362.png">

On mobile, only the first comment is shown;
Please, Is this the intended behaviour ?
If yes, will an update to address this be published soon.

**Comment by sgong-pdftron** [comment] 2022-03-03 18:04
Hi @damianimashaun you will be able to see replies on mobile if you enable collaboration:
https://github.com/PDFTron/pdftron-react-native/blob/master/API.md#collabenabled
Could you give it a try?

**Comment by damianimashaun** [comment] 2022-03-04 18:08
@sgong-pdftron I gave this a try and yes it works okay on iOS.
but the issue still happens on android.

In the example screenshots attached I added a single annotation, a comment and  some replies.
In Android, the comments list tab is empty:
![Screen 1](https://user-images.githubusercontent.com/49630919/156817460-e46e4fc1-6c8a-4a07-8d12-c9dea5c10407.jpg)

If I tap on the annotation and click comments, the comment is displayed, I can't tap on it to see the comments:
![Screen 2](https://user-images.githubusercontent.com/49630919/156817608-034ab79f-3dd7-4b55-9fdf-e350ec7bb9dd.jpg)

If I add a reply in the app, it is displayed correctly like screenshot below but its not displayed anymore if I exit the page and open again:
![screen 3](https://user-images.githubusercontent.com/49630919/156817787-e78dca5d-e2e8-40fc-96f7-0b9e1f2a4178.jpg)

Please help.

Also attached screenshots of what iOS looks like:
![iOS 1](https://user-images.githubusercontent.com/49630919/156817936-ce47d6d6-3f5e-40bc-8d08-7bfcfac61b67.png)
![iOS 2](https://user-images.githubusercontent.com/49630919/156817961-9f2c7145-07fa-4263-9368-7e7eb3adf213.png)

**Comment by sgong-pdftron** [comment] 2022-03-04 18:29
@damianimashaun could you provide the exact sample code (or ideally a project where we can reproduce as is) so we can try this on our end to further investigate? Thanks.

**Comment by damianimashaun** [comment] 2022-03-07 01:04
@sgong-pdftron I can reproduce here also, https://github.com/damianimashaun/pdftronSample
this is a bare project with only the sample code.
Thanks for checking it out.

**Comment by sgong-pdftron** [comment] 2022-03-08 17:14
@damianimashaun This is because your annotations are actually not XFDF command, they are regular XFDF. Commands starts with `<add>/<modify>/<delete> tags instead.
I have a fix for you with using "importAnnotations" instead:
https://github.com/PDFTron/pdftron-react-native/pull/517

Usage:

          annotationPromise = annotationPromise.then(async () => {
            await documentRef?.current?.importAnnotations(
              annotation.xfdf,
            );
          });

Demo:
![image](https://user-images.githubusercontent.com/20527369/157290064-a0facbfc-a89e-4c69-9bd5-56b3e39fa436.png)

You should be able to try it out once the fix PR is merged thanks.

**Closed** 2022-03-08 17:54 UTC
