### ISSUE TITLE
[Android] Note Annotations with replies are not clickable

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#518] opened 2022-03-09 11:18 UTC
**Describe the bug**
Note annotations with replies are not clickable, but they are, without replies
<img width="287" alt="image" src="https://user-images.githubusercontent.com/49630919/157430240-69692932-53ee-4eeb-8288-1e7bde7076ce.png">

like in the screenshot above, the note on the left has 2 replies, when tapped it does not bring up the context menu as seen on the right.
The note on the right has no replies.

**Steps to Reproduce the Problem**
use Shared code snippet

**Expected behavior**
When I tap on a Note annotation with/without comment or replies it should bring up the menu

**Screenshots**
see above

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: Android
 - Device: [e.g. iPhone6, Google Pixel 4]
 - OS: [e.g. iOS8.1, Android Nougat]

**Additional context**
**Please see attached snippet code for annotations/reproduction**
[App.js.txt](https://github.com/PDFTron/pdftron-react-native/files/8214175/App.js.txt)

**Comment by sgong-pdftron** [comment] 2022-03-09 22:55
@damianimashaun can reproduce, should be able to provide you with a fix in the next couple days. The issue is the replis has the same cooridnate as the actual sticky note, and on top of it, so it was trying to select the hidden comment instead. Thanks.

**Comment by sgong-pdftron** [comment] 2022-03-11 16:21
@damianimashaun the fix is in https://github.com/PDFTron/pdftron-react-native/issues/518, once it gets merged you can give it a try. With this fix you can select both:
![Screen Shot 2022-03-11 at 7 51 33 AM](https://user-images.githubusercontent.com/20527369/157906504-12f6cd75-b146-47a9-9061-fa660903c2f1.png)

**Closed** 2022-03-11 16:35 UTC
Labels: bug
